/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

/**
 *
 * @author Olivel
 */
public class ShortThoughtsManagerApp extends javax.swing.JFrame {

    /**
     * Creates new form ShortThoughtsManagerApp
     */
    public ShortThoughtsManagerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ThoughtsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EditingPanel = new javax.swing.JPanel();
        TemporaryPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Short Thoughts Manager");
        setName("ManagerFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        ThoughtsPanel.setBackground(new java.awt.Color(153, 255, 153));
        ThoughtsPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("This would be where the thoughts list go");
        ThoughtsPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(ThoughtsPanel);

        EditingPanel.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout EditingPanelLayout = new javax.swing.GroupLayout(EditingPanel);
        EditingPanel.setLayout(EditingPanelLayout);
        EditingPanelLayout.setHorizontalGroup(
            EditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        EditingPanelLayout.setVerticalGroup(
            EditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(EditingPanel);

        TemporaryPanel.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout TemporaryPanelLayout = new javax.swing.GroupLayout(TemporaryPanel);
        TemporaryPanel.setLayout(TemporaryPanelLayout);
        TemporaryPanelLayout.setHorizontalGroup(
            TemporaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        TemporaryPanelLayout.setVerticalGroup(
            TemporaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(TemporaryPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortThoughtsManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortThoughtsManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortThoughtsManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortThoughtsManagerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortThoughtsManagerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditingPanel;
    private javax.swing.JPanel TemporaryPanel;
    private javax.swing.JPanel ThoughtsPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
